In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
iris=load_iris()

KFold cross validation
basic example

In [3]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [4]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


Use KFold for our iris example

In [5]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [7]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []
scores_dt=[]


for train_index, test_index in folds.split(iris.data,iris.target):
    X_train, X_test, y_train, y_test = iris.data[train_index], iris.data[test_index], \
                                       iris.target[train_index], iris.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))
    scores_dt.append(get_score(DecisionTreeClassifier(),X_train,X_test,y_train,y_test))

In [9]:
print(scores_logistic,sum(scores_logistic))
print(scores_dt,sum(scores_dt))
print(scores_rf,sum(scores_rf))
print(scores_svm,sum(scores_svm))

[0.96, 0.96, 0.94] 2.86
[0.98, 0.94, 0.98] 2.9
[0.98, 0.94, 0.96] 2.88
[0.98, 0.98, 0.96] 2.92


## Cross score Validation

In [10]:
from sklearn.model_selection import cross_val_score

In [15]:
sl = cross_val_score(LogisticRegression(), iris.data, iris.target,cv=5)
sl

C:\Users\shubh\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [16]:
sr = cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target,cv=5)
sr

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])

In [18]:
sd = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target,cv=5)
sd

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [20]:
ss = cross_val_score(SVC(), iris.data, iris.target,cv=5)
ss

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])